declare query_parameters (customerName:string = "", startTime:datetime, endTime:datetime, supportProductNames:string = "[]");
let _productNames = todynamic(supportProductNames);
let _effectiveStart = iif((endTime - startTime) < 6h, startTime - 4h, startTime);
let _effectiveEnd = iif((endTime - startTime) < 6h, startTime + 4h, endTime);
cluster('https://supportrptwus3prod.westus3.kusto.windows.net').database('Product360M365').AllCloudsSupportIncidentWithReferenceModelVNext_AllSources 
| join kind=leftouter 
    ( cluster('supportrptwus3prod.westus3.kusto.windows.net').database('AceHubSupportData').
    MSaaSSupportCases 
    | where todatetime(CreatedOn) between(_effectiveStart .. _effectiveEnd) 
    | summarize arg_max(CosmosDbTs, IncidentId, Location) by CaseNumber
    | project IncidentId, Location) 
on $left.IncidentId == $right.IncidentId
| where CreatedDateTime between(_effectiveStart .. _effectiveEnd)
| where array_length(_productNames) == 0 or SupportProductName in (_productNames)
| where isempty(customerName) or Customer_CloudCustomerName contains customerName
| project CaseNumber = IncidentId, Title, State, IsCritSit, SupportProductName, Region = Location,
CreatedDateTime, IsEscalated, InitialSeverity, Severity, AzureSubscriptionId, Customer_CloudCustomerName