declare query_parameters (startTime:datetime, endTime:datetime, supportProductNames:string = "[]");
let _productNames = todynamic(supportProductNames);
let _effectiveStart = iif((endTime - startTime) < 6h, startTime - 4h, startTime);
let _effectiveEnd = endTime; //iif((endTime - startTime) < 6h, startTime + 4h, endTime);
cluster('https://supportrptwus3prod.westus3.kusto.windows.net').database('Product360M365').AllCloudsSupportIncidentWithReferenceModelVNext_AllSources 
| join kind=leftouter 
    ( cluster('supportrptwus3prod.westus3.kusto.windows.net').database('AceHubSupportData').
    MSaaSSupportCases 
    | where todatetime(CreatedOn) between(_effectiveStart .. _effectiveEnd) 
    | summarize arg_max(CosmosDbTs, IncidentId, Location) by CaseNumber
    | project IncidentId, Location) 
on $left.IncidentId == $right.IncidentId
| where CreatedDateTime between(_effectiveStart .. _effectiveEnd)
| where array_length(_productNames) == 0 or SupportProductName in (_productNames)
| summarize 
    TotalCaseCount = dcount(IncidentId),
    DistinctCustomerCount = dcount(Customer_CloudCustomerName),
    MaxSeverity = min(Severity),
    CritSitCount = countif(IsCritSit == true),
    DistinctCritSitCustomerCount = dcountif(Customer_CloudCustomerName, IsCritSit == true),
    CustomerList = make_set(Customer_CloudCustomerName),
    CritSitCustomerList = make_set_if(Customer_CloudCustomerName, IsCritSit == true),
    RegionList = make_set(Location),
    CritSitRegionList = make_set_if(Location, IsCritSit == true),
    CaseNumbers = make_set(IncidentId),
    CritSitCaseNumbers = make_set_if(IncidentId, IsCritSit == true),
    EarliestCase = min(CreatedDateTime),
    LatestCase = max(CreatedDateTime)
    by SupportProductName
| where DistinctCustomerCount >= 2
| project SupportProductName, TotalCaseCount, DistinctCustomerCount, MaxSeverity, 
    CritSitCount, DistinctCritSitCustomerCount, CustomerList, CritSitCustomerList,
    RegionList, CritSitRegionList, CaseNumbers, CritSitCaseNumbers, EarliestCase, LatestCase
